name: test

on:
  push:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Install Rust 1.61.0
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.61.0
          override: true
          components: rustfmt, clippy
    - uses: actions/checkout@v3
    - name: Coverage
      run: make coverage
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error:     true